### ISSUE TITLE
给up说一下，你好像没有给exe留配置的机会喔。

### ISSUE THREAD

**Issue by detesion** [aDm8H/b-fans-recorder-server#1]
exe文件并没有global-config的配置文件。要怎么配置嘞

**Comment by aDm8H** [comment]
首次运行后，会在exe相同目录自动创建 global-config.json 文件，在此可进行基本的配置（目标用户UID、轮询间隔、WS服务器建立端口）。

**Comment by detesion** [comment]
刚刚去试了一下没有诶

**Comment by aDm8H** [comment]
抱歉，经检查，系可执行文件打包时出现错误，导致程序无法正常运行，将在未来进行修复。建议先使用Node源码方式运行程序，感谢您的支持！

**Comment by aDm8H** [comment]
> 刚刚去试了一下没有诶

已经更新了[Release](https://github.com/aDm8H/b-fans-recorder-server/releases/tag/v1.0.1)可执行文件，可前往下载。
